### PR TITLE
Feat/deliverable2

### PR DESCRIPTION
**Pull request by EArcigaV**
## 1.- Cart and Login module.
Screen Shot 2022-07-14 at 17 58 01
Screen Shot 2022-07-14 at 17 58 55

## 2.- Responsive views.
Screen Shot 2022-07-09 at 10 13 46
Screen Shot 2022-07-08 at 17 38 52
Screen Shot 2022-07-08 at 17 39 12

### CODE REVIEW

**Review by marcoromerowizeline — CHANGES_REQUESTED** [review]
Hi Lalo. I noticed when the product quantity changes, I do not see any change in the total items in the summary section. Please consider including this behavior in your final delivery.

**Comment by marcoromerowizeline** [comment]
Also, it could be great if you apply the new approach for this second delivery that you proposed in our Slack conversation to change the logic of your solution. For the reasons that we talked about previously. Thanks Lalo.

**Comment by EArcigaV** [comment]
> Also, it could be great if you apply the new approach for this second delivery that you proposed in our Slack conversation to change the logic of your solution. For the reasons that we talked about previously. Thanks Lalo.

Done.

**Comment by EArcigaV** [comment]
> Also, it could be great if you apply the new approach for this second delivery that you proposed in our Slack conversation to change the logic of your solution. For the reasons that we talked about previously. Thanks Lalo.

Done.

**Comment by EArcigaV** [comment]
> Hi Lalo. I noticed when the product quantity changes, I do not see any change in the total items in the summary section. Please consider including this behavior in your final delivery.

Sure. Thank You.

**Review by marcoromerowizeline — APPROVED** [review]
Hi Lalo. Thank you for your PR. I see that the quantity input does not change the total price of each product in the Cart module, neither the total items nor the total price in the Summary.

**Pull request merged**
